# coding: utf-8

# flake8: noqa
"""
    TurboSMTP Public APIs

    This document describes all public turboSMTP **V2** API and offers endpoints Descriptions, Parameters, Requests, Responses and Samples of usage.  [Click here to view the previous version of turboSMTP Public API Version 1.0](https://www.serversmtp.com/turbo-api-1)   # Security For the most part (and where not otherwise explicit) turboSMTP’s API requires Authorization.   Authorization to access a user’s resource is granted to clients provided they set  authentication headers into their request, valued with the proper values issued by turboSMTP servers.  ## *  Authorization via ConsumerKey/ConsumerSecret  This type of authorization consists of a pair of headers, named consumerKey and consumerSecret that are created and granted to the end user to be used in a permanent way (unless they´re deleted of course). This kind of authentication is intended to provide access to endpoints features without the need of providing the user the account details (email address + password).  *consumerKey:* Consumer Key Granted.  *consumerSecret:* Consumer Secret Granted.  (Use [/consumerKeys/create](#/consumerkey/createConsumerKey) create a consumer key/secret pair).      ## *  Authorization via Authentication Key  The authentication key is user-based and it is issued by turboSMTP servers upon successful user’s email address + password challenge, performed by means of appropriate request.      *Authorization:* Authorization_Key  (Use [/authentication/authorize](#/authentication/AuthenticationLogin) to obtain an API Key)  # Data Interchange Format  For the most part (and where not otherwise explicit) turboSMTP’s API uses JSON as the data format of choice when it comes to request and response bodies.       

    The version of the OpenAPI document: 2.0.0-oas3
    Contact: api@turbo-smtp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from API_TurboSMTP.models.agency_settings import AgencySettings
from API_TurboSMTP.models.alert import Alert
from API_TurboSMTP.models.alert_base import AlertBase
from API_TurboSMTP.models.alert_list_sucess_responset_body import AlertListSucessResponsetBody
from API_TurboSMTP.models.analytic_filter_by import AnalyticFilterBy
from API_TurboSMTP.models.analytic_filter_by_option import AnalyticFilterByOption
from API_TurboSMTP.models.analytic_mail_item import AnalyticMailItem
from API_TurboSMTP.models.analytic_mail_status import AnalyticMailStatus
from API_TurboSMTP.models.analytic_order_by import AnalyticOrderBy
from API_TurboSMTP.models.analytics_list_sucess_responset_body import AnalyticsListSucessResponsetBody
from API_TurboSMTP.models.attachment import Attachment
from API_TurboSMTP.models.authentication import Authentication
from API_TurboSMTP.models.authentication_login_request_body import AuthenticationLoginRequestBody
from API_TurboSMTP.models.authentication_login_sucess_responset_body import AuthenticationLoginSucessResponsetBody
from API_TurboSMTP.models.authorization_error import AuthorizationError
from API_TurboSMTP.models.base_agency_settings import BaseAgencySettings
from API_TurboSMTP.models.buy_email_validator_credits_bad_request_response_body import BuyEmailValidatorCreditsBadRequestResponseBody
from API_TurboSMTP.models.buy_email_validator_credits_request import BuyEmailValidatorCreditsRequest
from API_TurboSMTP.models.buy_email_validator_credits_sucess_response import BuyEmailValidatorCreditsSucessResponse
from API_TurboSMTP.models.change_password_bad_request_response_body import ChangePasswordBadRequestResponseBody
from API_TurboSMTP.models.change_password_request_body import ChangePasswordRequestBody
from API_TurboSMTP.models.check_validity_token_reset_password_bad_request_response_body import CheckValidityTokenResetPasswordBadRequestResponseBody
from API_TurboSMTP.models.commmon_result_response_body import CommmonResultResponseBody
from API_TurboSMTP.models.common_bad_request_response_body import CommonBadRequestResponseBody
from API_TurboSMTP.models.common_message_response_body import CommonMessageResponseBody
from API_TurboSMTP.models.common_success_response_body import CommonSuccessResponseBody
from API_TurboSMTP.models.consumer_key import ConsumerKey
from API_TurboSMTP.models.consumer_key_create_request_body import ConsumerKeyCreateRequestBody
from API_TurboSMTP.models.consumer_key_create_response_body import ConsumerKeyCreateResponseBody
from API_TurboSMTP.models.consumer_key_list_sucess_responset_body import ConsumerKeyListSucessResponsetBody
from API_TurboSMTP.models.country import Country
from API_TurboSMTP.models.currency import Currency
from API_TurboSMTP.models.email import Email
from API_TurboSMTP.models.email1 import Email1
from API_TurboSMTP.models.email_address_request_body import EmailAddressRequestBody
from API_TurboSMTP.models.email_request_body import EmailRequestBody
from API_TurboSMTP.models.email_validation_upload_response import EmailValidationUploadResponse
from API_TurboSMTP.models.email_validator_list import EmailValidatorList
from API_TurboSMTP.models.email_validator_list_delete_success import EmailValidatorListDeleteSuccess
from API_TurboSMTP.models.email_validator_list_email_details import EmailValidatorListEmailDetails
from API_TurboSMTP.models.email_validator_mail_details import EmailValidatorMailDetails
from API_TurboSMTP.models.email_validator_mail_details_basic import EmailValidatorMailDetailsBasic
from API_TurboSMTP.models.email_validator_mail_shared_details import EmailValidatorMailSharedDetails
from API_TurboSMTP.models.email_validator_status_summary_item import EmailValidatorStatusSummaryItem
from API_TurboSMTP.models.email_validator_subscription import EmailValidatorSubscription
from API_TurboSMTP.models.email_validator_sucess_responset_body import EmailValidatorSucessResponsetBody
from API_TurboSMTP.models.email_validator_upload_bad_request_response_body import EmailValidatorUploadBadRequestResponseBody
from API_TurboSMTP.models.email_validator_validate_bad_request_response_body import EmailValidatorValidateBadRequestResponseBody
from API_TurboSMTP.models.email_validator_validate_list_bad_request_response_body import EmailValidatorValidateListBadRequestResponseBody
from API_TurboSMTP.models.email_validator_validated_mails_results import EmailValidatorValidatedMailsResults
from API_TurboSMTP.models.logo import Logo
from API_TurboSMTP.models.order_type import OrderType
from API_TurboSMTP.models.send_bad_request_response_body import SendBadRequestResponseBody
from API_TurboSMTP.models.send_secret_token_reset_password_bad_request_response_body import SendSecretTokenResetPasswordBadRequestResponseBody
from API_TurboSMTP.models.send_secret_token_reset_password_request_body import SendSecretTokenResetPasswordRequestBody
from API_TurboSMTP.models.send_sucess_responset_body import SendSucessResponsetBody
from API_TurboSMTP.models.send_unauthorized_response_body import SendUnauthorizedResponseBody
from API_TurboSMTP.models.smtp_limit_interval import SmtpLimitInterval
from API_TurboSMTP.models.state import State
from API_TurboSMTP.models.sub_account_list_sucess_responset_body import SubAccountListSucessResponsetBody
from API_TurboSMTP.models.subaccount import Subaccount
from API_TurboSMTP.models.subaccount_active_plan import SubaccountActivePlan
from API_TurboSMTP.models.subaccount_active_status import SubaccountActiveStatus
from API_TurboSMTP.models.subaccount_base import SubaccountBase
from API_TurboSMTP.models.subaccount_create_request import SubaccountCreateRequest
from API_TurboSMTP.models.subaccount_id_status_base import SubaccountIDStatusBase
from API_TurboSMTP.models.subaccount_ip import SubaccountIP
from API_TurboSMTP.models.subaccount_list_item import SubaccountListItem
from API_TurboSMTP.models.subaccount_password_confirm_password import SubaccountPasswordConfirmPassword
from API_TurboSMTP.models.subaccount_plan_base import SubaccountPlanBase
from API_TurboSMTP.models.subaccount_smtp_limit import SubaccountSMTPLimit
from API_TurboSMTP.models.subaccount_update_request import SubaccountUpdateRequest
from API_TurboSMTP.models.suppression import Suppression
from API_TurboSMTP.models.suppression_filter_by import SuppressionFilterBy
from API_TurboSMTP.models.suppression_filter_order_page_request_body import SuppressionFilterOrderPageRequestBody
from API_TurboSMTP.models.suppression_filter_order_request_body import SuppressionFilterOrderRequestBody
from API_TurboSMTP.models.suppression_filter_request_body import SuppressionFilterRequestBody
from API_TurboSMTP.models.suppression_import_json import SuppressionImportJson
from API_TurboSMTP.models.suppression_operator import SuppressionOperator
from API_TurboSMTP.models.suppression_order_by import SuppressionOrderBy
from API_TurboSMTP.models.suppression_restrict_by import SuppressionRestrictBy
from API_TurboSMTP.models.suppression_restriction import SuppressionRestriction
from API_TurboSMTP.models.suppression_source import SuppressionSource
from API_TurboSMTP.models.suppression_upload_bad_request_response_body import SuppressionUploadBadRequestResponseBody
from API_TurboSMTP.models.suppression_upload_response import SuppressionUploadResponse
from API_TurboSMTP.models.suppressions_delete_success import SuppressionsDeleteSuccess
from API_TurboSMTP.models.suppressions_sucess_responset_body import SuppressionsSucessResponsetBody
from API_TurboSMTP.models.update_reset_password_bad_request_response_body import UpdateResetPasswordBadRequestResponseBody
from API_TurboSMTP.models.update_reset_password_request_body import UpdateResetPasswordRequestBody
