# coding: utf-8

"""
    TurboSMTP Public APIs

    This document describes all public turboSMTP **V2** API and offers endpoints Descriptions, Parameters, Requests, Responses and Samples of usage.  [Click here to view the previous version of turboSMTP Public API Version 1.0](https://www.serversmtp.com/turbo-api-1)   # Security For the most part (and where not otherwise explicit) turboSMTP’s API requires Authorization.   Authorization to access a user’s resource is granted to clients provided they set  authentication headers into their request, valued with the proper values issued by turboSMTP servers.  ## *  Authorization via ConsumerKey/ConsumerSecret  This type of authorization consists of a pair of headers, named consumerKey and consumerSecret that are created and granted to the end user to be used in a permanent way (unless they´re deleted of course). This kind of authentication is intended to provide access to endpoints features without the need of providing the user the account details (email address + password).  *consumerKey:* Consumer Key Granted.  *consumerSecret:* Consumer Secret Granted.  (Use [/consumerKeys/create](#/consumerkey/createConsumerKey) create a consumer key/secret pair).      ## *  Authorization via Authentication Key  The authentication key is user-based and it is issued by turboSMTP servers upon successful user’s email address + password challenge, performed by means of appropriate request.      *Authorization:* Authorization_Key  (Use [/authentication/authorize](#/authentication/AuthenticationLogin) to obtain an API Key)  # Data Interchange Format  For the most part (and where not otherwise explicit) turboSMTP’s API uses JSON as the data format of choice when it comes to request and response bodies.       

    The version of the OpenAPI document: 2.0.0-oas3
    Contact: api@turbo-smtp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from API_TurboSMTP.models.currency import Currency
from typing import Optional, Set
from typing_extensions import Self

class EmailValidatorSubscription(BaseModel):
    """
    EmailValidatorSubscription
    """ # noqa: E501
    currency: Currency
    free_credits: Annotated[int, Field(strict=True, ge=0)] = Field(description="Ammount of allocated free credits.")
    free_credits_used: Annotated[int, Field(strict=True, ge=0)] = Field(description="Ammount of used free credits.")
    last_used_period: Optional[Annotated[str, Field(strict=True)]] = Field(description="Last time credit was used.")
    latest_period_start_date: Optional[Annotated[str, Field(strict=True)]] = Field(description="Free credit period start date (renewed each cycle).")
    period_expiration_date: Optional[Annotated[str, Field(strict=True)]] = Field(description="Free credit period expiration date.")
    paid_credits: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Amount of remaining money specified in the 'currency' field value currency.")
    remaining_free_credit: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Ammount of remaining free credits.")
    __properties: ClassVar[List[str]] = ["currency", "free_credits", "free_credits_used", "last_used_period", "latest_period_start_date", "period_expiration_date", "paid_credits", "remaining_free_credit"]

    @field_validator('last_used_period')
    def last_used_period_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})", value):
            raise ValueError(r"must validate the regular expression /(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})/")
        return value

    @field_validator('latest_period_start_date')
    def latest_period_start_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})", value):
            raise ValueError(r"must validate the regular expression /(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})/")
        return value

    @field_validator('period_expiration_date')
    def period_expiration_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})", value):
            raise ValueError(r"must validate the regular expression /(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmailValidatorSubscription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if last_used_period (nullable) is None
        # and model_fields_set contains the field
        if self.last_used_period is None and "last_used_period" in self.model_fields_set:
            _dict['last_used_period'] = None

        # set to None if latest_period_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.latest_period_start_date is None and "latest_period_start_date" in self.model_fields_set:
            _dict['latest_period_start_date'] = None

        # set to None if period_expiration_date (nullable) is None
        # and model_fields_set contains the field
        if self.period_expiration_date is None and "period_expiration_date" in self.model_fields_set:
            _dict['period_expiration_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmailValidatorSubscription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": obj.get("currency"),
            "free_credits": obj.get("free_credits"),
            "free_credits_used": obj.get("free_credits_used"),
            "last_used_period": obj.get("last_used_period"),
            "latest_period_start_date": obj.get("latest_period_start_date"),
            "period_expiration_date": obj.get("period_expiration_date"),
            "paid_credits": obj.get("paid_credits"),
            "remaining_free_credit": obj.get("remaining_free_credit")
        })
        return _obj


