# coding: utf-8

"""
    TurboSMTP Public APIs

    This document describes all public turboSMTP **V2** API and offers endpoints Descriptions, Parameters, Requests, Responses and Samples of usage.  [Click here to view the previous version of turboSMTP Public API Version 1.0](https://www.serversmtp.com/turbo-api-1)   # Security For the most part (and where not otherwise explicit) turboSMTP’s API requires Authorization.   Authorization to access a user’s resource is granted to clients provided they set  authentication headers into their request, valued with the proper values issued by turboSMTP servers.  ## *  Authorization via ConsumerKey/ConsumerSecret  This type of authorization consists of a pair of headers, named consumerKey and consumerSecret that are created and granted to the end user to be used in a permanent way (unless they´re deleted of course). This kind of authentication is intended to provide access to endpoints features without the need of providing the user the account details (email address + password).  *consumerKey:* Consumer Key Granted.  *consumerSecret:* Consumer Secret Granted.  (Use [/consumerKeys/create](#/consumerkey/createConsumerKey) create a consumer key/secret pair).      ## *  Authorization via Authentication Key  The authentication key is user-based and it is issued by turboSMTP servers upon successful user’s email address + password challenge, performed by means of appropriate request.      *Authorization:* Authorization_Key  (Use [/authentication/authorize](#/authentication/AuthenticationLogin) to obtain an API Key)  # Data Interchange Format  For the most part (and where not otherwise explicit) turboSMTP’s API uses JSON as the data format of choice when it comes to request and response bodies.       

    The version of the OpenAPI document: 2.0.0-oas3
    Contact: api@turbo-smtp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from API_TurboSMTP.models.email_validator_status_summary_item import EmailValidatorStatusSummaryItem
from typing import Optional, Set
from typing_extensions import Self

class EmailValidatorList(BaseModel):
    """
    EmailValidatorList
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Email validation list id.")
    creation_time: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Date and Time of the validation list creation.")
    file_name: Optional[StrictStr] = Field(default=None, description="File name of the uploaded file.")
    is_processed: Optional[StrictBool] = Field(default=None, description="True if the validation list was already processed.")
    percentage: Optional[StrictInt] = Field(default=None, description="Describes the percentage progress of validation list.")
    total_emails: Optional[StrictInt] = Field(default=None, description="Amount of email addresses in the validation list.")
    total_processed: Optional[StrictInt] = Field(default=None, description="Describes the count of email addresses processed so far.")
    status_summary: Optional[List[EmailValidatorStatusSummaryItem]] = None
    __properties: ClassVar[List[str]] = ["id", "creation_time", "file_name", "is_processed", "percentage", "total_emails", "total_processed", "status_summary"]

    @field_validator('creation_time')
    def creation_time_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})", value):
            raise ValueError(r"must validate the regular expression /(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmailValidatorList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in status_summary (list)
        _items = []
        if self.status_summary:
            for _item in self.status_summary:
                if _item:
                    _items.append(_item.to_dict())
            _dict['status_summary'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmailValidatorList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "creation_time": obj.get("creation_time"),
            "file_name": obj.get("file_name"),
            "is_processed": obj.get("is_processed"),
            "percentage": obj.get("percentage"),
            "total_emails": obj.get("total_emails"),
            "total_processed": obj.get("total_processed"),
            "status_summary": [EmailValidatorStatusSummaryItem.from_dict(_item) for _item in obj["status_summary"]] if obj.get("status_summary") is not None else None
        })
        return _obj


